name: Deploy Hugo to GitHub Pages (legacy but stable)

on:
  push:
    branches: [master]

permissions:
  contents: write  # Para poder hacer push a gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.113.0

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Instalar Hugo
        run: |
          wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i hugo.deb

      - name: Instalar Dart Sass
        run: sudo snap install dart-sass

      - name: Construir sitio
        run: hugo --minify

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
